### ISSUE TITLE
fog_x.Dataset with relative path is not supported

### ISSUE THREAD

**Issue by J-HowHuang** [BerkeleyAutomation/fog_x#12]
**Describe the bug**
fog_x cannot parse relative path while creating a dataset with local relative path as the dataset path

**To Reproduce**
```
import fog_x

dataset1 = fog_x.Dataset(
    name="demo_ds_1",
    path="./test_dataset"
)  
```

**Expected behavior**

**Screenshots**
```
I 2024-04-29 23:12:44,406 dataset.py:104] Dataset path: ./test_dataset
I 2024-04-29 23:12:44,406 dataset.py:125] Path does not exist. (./test_dataset/demo_ds_1)
I 2024-04-29 23:12:44,406 dataset.py:37] Creating bucket 't_dataset' in cloud provider './' with folder 'demo_ds_1/'...
Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fogxstore-nGESZMNh-py3.10/lib/python3.10/site-packages/fog_x/dataset.py", line 123, in __init__
    step_data_connector = LazyFrameConnector(f"{path}/{name}")
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fogxstore-nGESZMNh-py3.10/lib/python3.10/site-packages/fog_x/database/polars_connector.py", line
169, in __init__
    ds.dataset(self.path, format="parquet")
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fogxstore-nGESZMNh-py3.10/lib/python3.10/site-packages/pyarrow/dataset.py", line 782, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fogxstore-nGESZMNh-py3.10/lib/python3.10/site-packages/pyarrow/dataset.py", line 465, in _filesys
tem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fogxstore-nGESZMNh-py3.10/lib/python3.10/site-packages/pyarrow/dataset.py", line 441, in _ensure_
single_source
    raise FileNotFoundError(path)
FileNotFoundError: ./test_dataset/demo_ds_1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/FogX-Store/examples/example_fogx_collector.py", line 5, in <module>
    dataset1 = fog_x.Dataset(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fogxstore-nGESZMNh-py3.10/lib/python3.10/site-packages/fog_x/dataset.py", line 128, in __init__
    create_cloud_bucket_if_not_exist(cloud_provider, bucket_name, f"{name}/")
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/fogxstore-nGESZMNh-py3.10/lib/python3.10/site-packages/fog_x/dataset.py", line 66, in create_clou
d_bucket_if_not_exist
    raise ValueError(f"Unsupported cloud provider '{provider}'.")
ValueError: Unsupported cloud provider './'.
```

**Desktop (please complete the following information):**

**Additional context**

**Comment by KeplerC** [comment]
should be fixed by 00bbb7f. LMK if there are any issues
